/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./public/book.glb -o ./src/components/Book.jsx 
*/

import { useGLTF } from "@react-three/drei";
import { useSpring, animated } from "@react-spring/three";

export function BookModel({ sceneAn }) {
  const { nodes, materials } = useGLTF("/book.glb");
  const { rotation, position } = useSpring({
    rotation:
      sceneAn == 2
        ? [0, 0, 0]
        : sceneAn == 3
        ? [0, 4.5, 0]
        : sceneAn == 4
        ? [0, 10.5, 0]
        : sceneAn == 5
        ? [0, 17, 0]
        : [0, 0, 0],
    position:
      sceneAn == 2
        ? [0, 0, 0]
        : [0, 0, 0],
    config: { tension: 100, friction: 50 },
  });
  return (
    <group scale={1} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          geometry={nodes.Object_2.geometry}
          material={materials["lambert2.001"]}
        />
        <mesh
          castShadow
          geometry={nodes.Object_3.geometry}
          material={materials["surfaceShader5.001"]}
        />
        <animated.mesh
          rotation={rotation}
          castShadow
          geometry={nodes.Object_4.geometry}
          material={materials["surfaceShader7.001"]}
        />
        <mesh
          castShadow
          geometry={nodes.Object_5.geometry}
          material={materials["surfaceShader8.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/book.glb");
